name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx run-many -t lint test build typecheck
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npx nx fix-ci
        if: always()

      - name: Upload backend-services artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: backend-services
          path: apps/backend-services/dist

      - name: Upload api-gateway artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: api-gateway
          path: apps/api-gateway/dist

  deploy-backend-services:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend-services artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-services
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3B5C7935BAEF49B9828DBAD6A0AC9DC3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_609739FAB3464F7A974078B07FBA4476 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_161B6B2034BB469D809DA8A9FBC4B3EB }}

      - name: Deploy to Azure Web App - backend-services
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-services'
          slot-name: 'Production'
          package: .

  deploy-api-gateway:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download api-gateway artifact
        uses: actions/download-artifact@v4
        with:
          name: api-gateway
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC072F3F67A44D909AF4C9FF54FD3189 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56E923D72F334F67B4C52CE35FB2DBC0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83A70AFFF63542C688E3DC4B566EF8C7 }}

      - name: Deploy to Azure Web App - api-gateway
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vistone-api-gateway'
          slot-name: 'Production'
          package: .
