name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Note: prisma:generate runs automatically as a dependency of ai-engine:test
      - run: npx nx run-many -t lint test build typecheck
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npx nx fix-ci
        if: always()

      - name: Upload ai-engine artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: ai-engine
          path: apps/ai-engine/dist

      - name: Upload auth-service artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: auth-service
          path: apps/auth-service/dist

      - name: Upload project-management artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: project-management
          path: apps/project-management/dist

      - name: Upload workforce-management artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: workforce-management
          path: apps/workforce-management/dist

      - name: Upload api-gateway artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: api-gateway
          path: apps/api-gateway/dist

  deploy-ai-engine:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download ai-engine artifact
        uses: actions/download-artifact@v4
        with:
          name: ai-engine
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B55D711FBB94E95908EA48AD90BBC02 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_468A61869C464E81AEEB90CB9213D1FE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5BE7F4F5E1AD45E493F33923D108BB48 }}

      - name: Deploy to Azure Web App - ai-service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ai-service'
          slot-name: 'Production'
          package: .

  deploy-auth-service:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download auth-service artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-service
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DFE62C5777844C2E888423576E49CC5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75A416280FC240BDB8AF52C71DE04B2A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E47D11926174493900C2392A1814A12 }}

      - name: Deploy to Azure Web App - auth-service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vistone-auth-service'
          slot-name: 'Production'
          package: .

  deploy-project-management:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download project-management artifact
        uses: actions/download-artifact@v4
        with:
          name: project-management
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1DA85C3625234F34BACF35D62D4AC3E9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_434D904CDF1543F28A04C31964CD0C04 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_49A445D8C7FF4BAA943158241190BAD2 }}

      - name: Deploy to Azure Web App - project-management
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vistone-project'
          slot-name: 'Production'
          package: .

  deploy-workforce-management:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download workforce-management artifact
        uses: actions/download-artifact@v4
        with:
          name: workforce-management
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_799BC13C13D448C7AA4A339F8EE20C7A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8F6059642EAC4278AEF433AC8C6D3E91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8A0AF564F9264640B7E7D98A008616F6 }}

      - name: Deploy to Azure Web App - workforce-management
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'workforce'
          slot-name: 'Production'
          package: .

  deploy-api-gateway:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download api-gateway artifact
        uses: actions/download-artifact@v4
        with:
          name: api-gateway
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC072F3F67A44D909AF4C9FF54FD3189 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56E923D72F334F67B4C52CE35FB2DBC0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_83A70AFFF63542C688E3DC4B566EF8C7 }}

      - name: Deploy to Azure Web App - api-gateway
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vistone-api-gateway'
          slot-name: 'Production'
          package: .
